### ISSUE TITLE
Впрос по webpack

### ISSUE THREAD

**Issue by lol1pop** [unpub777/PersonalPortal#1]
**в статье вы пишите мол что подключаете сборку веб пака** 

> Далее перейдем в файл Startup.cs и пропишем middleware магию, о которой говорилось выше. Для этого нам необходимо поставить пакет Microsoft.AspNetCore.SpaServices, ну или он уже есть в составе пакета Microsoft.AspNetCore.All.

> if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
		app.UseWebpackDevMiddleware(); // 1
	}

> В строке 1 мы включаем поддержку webpack, теперь у нас не будет болеть голова за сборку клиентских ресурсов и нам не нужно будет каждый раз вручную ее запускать, прописывать куда нибудь в PostBuildEvents или держать открытым окошко консоли с запущенной webpack –watch. Этой строкой мы создаем инстанс webpack-а в памяти, который будет отслеживать изменения в файлах и запускать инкрементальную сборку. 

**Но тут на github в итоге нет этой строчке в файле _Startup.cs_, и вообще не понятно как у вас собирается проект реакта... но при этом _webpack.config.js_ есть , просмотрел все ваши коммиты так и не понял каким способом вы дергаете этот фаил чтобы собрать реакт**

**Comment by unpub777** [comment]
Привет.
Да, есть некоторые расхождения между статьей и исходниками на гитхабе.
Тут клиентский код собирается вызовом webpack-а в PostBuildEvent.

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="node node_modules/webpack/bin/webpack.js" />
  </Target>

**Comment by lol1pop** [comment]
Спасибо)
А  в Post-Build Event вы просто пропписывате `npx webpack --config webpack.config.js` ??

**Comment by unpub777** [comment]
```
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="node node_modules/webpack/bin/webpack.js" />
  </Target>
```
